"""CLL trajectory replication across GSM8K and SVAMP: per-model L0->L5 median-margin
shift, Mann-Whitney p, Spearman trend, and verdict. Emits a LaTeX table for the paper."""
import json, os, statistics as st
from scipy import stats

ROOT = "results/phase6_legibility/cll_gaivi"      # <model>/{gsm8k,svamp}/level_*.cll.jsonl
LF = {0: "level_0_clean", 2: "level_2_blur_light",
      4: "level_4_blur_noise", 5: "level_5_heavy_degradation"}
DISPLAY = {
    "Qwen2.5-VL-7B-Instruct": "Qwen2.5-VL-7B", "Qwen2-VL-2B-Instruct": "Qwen2-VL-2B",
    "Idefics3-8B-Llama3": "Idefics3-8B", "Phi-3.5-vision-instruct": "Phi-3.5",
    "llava-onevision-qwen2-7b-ov-hf": "LLaVA-OV-7B", "llava-v1.6-mistral-7b-hf": "LLaVA-1.6-7B",
}


def margins(model, L, bench):
    p = os.path.join(ROOT, model, bench, f"{LF[L]}.cll.jsonl")
    out = []
    if not os.path.exists(p):
        return out
    for line in open(p, encoding="utf-8"):
        r = json.loads(line)
        if r.get("margin"):
            out.append(r["margin"]["margin_mean"])
    return out


def stats_for(model, bench):
    per = {L: margins(model, L, bench) for L in (0, 2, 4, 5)}
    if not per[0] or not per[5]:
        return None
    _, pu = stats.mannwhitneyu(per[5], per[0], alternative="two-sided")
    xs, ys = [], []
    for L in (0, 2, 4, 5):
        xs += [L] * len(per[L]); ys += per[L]
    rho, _ = stats.spearmanr(xs, ys)
    d = st.median(per[5]) - st.median(per[0])
    rises = d > 0 and pu < 0.05 and rho > 0
    return d, pu, rho, ("$\\uparrow$" if rises else "--")


models = sorted(DISPLAY, key=lambda m: -(stats_for(m, "gsm8k") or (0,))[0])
print("% --- CLL replication table (auto-generated by cll_replication_table.py) ---")
print("\\begin{table}[t]\\centering\\small")
print("\\begin{tabular}{lccc@{\\hspace{1.2em}}ccc}")
print("\\toprule")
print(" & \\multicolumn{3}{c}{GSM8K} & \\multicolumn{3}{c}{SVAMP} \\\\")
print("\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}")
print("Model & $\\Delta$med & $p$ & & $\\Delta$med & $p$ & \\\\")
print("\\midrule")
for m in models:
    g = stats_for(m, "gsm8k")
    s = stats_for(m, "svamp")
    if not g or not s:
        continue
    print(f"{DISPLAY[m]} & {g[0]:+.2f} & {g[1]:.0e} & {g[3]} "
          f"& {s[0]:+.2f} & {s[1]:.0e} & {s[3]} \\\\")
print("\\bottomrule")
print("\\end{tabular}")
print("\\caption{CLL arbitration-margin trajectory (L0$\\to$L5) per model on both "
      "benchmarks: median-margin shift $\\Delta$med, Mann--Whitney $p$, and verdict "
      "($\\uparrow$ = significant graded rise). All six per-model verdicts agree across "
      "GSM8K and SVAMP.}")
print("\\label{tab:cll_replication}")
print("\\end{table}")
